# 指定基础镜像，在ubuntu linux系统中运行
FROM ubuntu:22.04
# 将apt-get源更换为国内源
RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
RUN sed -i 's/security.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
# 构建linux基础环境
RUN apt update && \
apt install -y autoconf automake autotools-dev curl \
libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex \
texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev pkg-config \
git libusb-1.0-0-dev device-tree-compiler default-jdk gnupg vim bash bash-completion \
help2man perl python3 make clang libfl2 libfl-dev zlib1g libsystemc libsystemc-dev
# 将默认shell从dash修改为bash
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
# 下载RISC-V GNU Toolchain，分支为master分支（暂时不用）
#RUN git clone -b master --single-branch https://gitee.com/IC_MASTER/riscv-gnu-toolchain.git && \
#cd riscv-gnu-toolchain && \
#git checkout && \
#git submodule update --init --recursive 
# 下载RISC-V test测试集（暂时不用）
# 下载sbt软件
RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list && \
echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list && \
curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | tee /etc/apt/trusted.gpg.d/sbt.asc && \
apt-get update && \
apt-get install -y sbt
# 安装verilator
RUN git clone https://gitee.com/IC_MASTER/verilator.git && \
cd verilator && \
echo 'export VERILATOR_ROOT=`pwd`' >> ~/.bashrc && \
echo 'export PATH=$VERILATOR_ROOT/bin:$PATH' >> ~/.bashrc && \
source ~/.bashrc && \
autoconf && ./configure && make -j `nproc`
# 下载chisel-template
RUN git clone https://gitee.com/IC_MASTER/chisel-template
# 如果系统是ARM架构CPU（如MACBOOK M2），需要手动编译firtool，目前chisel依赖中没有linux-aarch64版本
